# Generated by Django 5.0.7 on 2025-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='passwod', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuestFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('para', models.CharField(choices=[('2', 'Со второй половинкой'), ('1', 'Один/Одна'), ('0', 'Не получится придти')], default='1', max_length=1)),
            ],
        ),
    ]
